on:
  schedule:
  - cron: "15 * * * *"
  push:
    branches:
      - main

name: update-data

jobs:
  render:
    name: update-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rocker/tidyverse:latest
      - name: Install packages
        run: |
          install.packages("remotes")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript data-raw/actions-update-data.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data-raw/xlsx
          git add data-raw/html
          git add data-raw/xml
          git add data
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
