on:
  schedule:
  - cron: "15 * * * *"
  push:
    branches:
      - main

name: atualizar-dados-cpi

jobs:
  render:
    name: update-data
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalar pacotes e dependências
        run: |
          install.packages("remotes")
          install.packages("progressr")
          install.packages("glue")
          install.packages("fs")
          install.packages("janitor")
          install.packages("writexl")
          install.packages("genderBR")
          remotes::install_github("abjur/abjutils")
        shell: Rscript {0}
      - name: Rodar script de raspagem de dados
        run: |
          Rscript data-raw/update-data.R
      - name: Commita resultados
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data-raw/xlsx
          git add data-raw/html
          git add data-raw/xml
          git add data
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
