on:
  schedule:
  - cron: "15 * * * *"
  push:
    branches:
      - main

name: update-data

jobs:
  render:
    name: update-data
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          install.packages("remotes")
          install.packages("progressr")
          install.packages("glue")
          install.packages("fs")
          install.packages("janitor")
          install.packages("writexl")
          install.packages("genderBR")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript data-raw/update-data.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data-raw/xlsx
          git add data-raw/html
          git add data-raw/xml
          git add data
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
